config/routes.rb
Rails.application.routes.draw do

  root 'projects#index'

  get '/signup' => 'users#new'
  post 'signup' => 'users#create'

  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :projects do
    resources :tasks
    resources :features
  end

  resources :tasks

  resources :features
  

end

app/models/feature.rb
class Feature < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true, allow_blank: true
  validates_associated :project, on: :update

  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true
  #validates :dev_env, allow_blank: true
  #validates :prod_env,  allow_blank: true
  #validates :language_desc, allow_blank: true

  has_many :task, dependent: :destroy
  has_many :feature, dependent: :destroy
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true, allow_blank: true
  validates :status, presence: true, allow_blank: true
  validates_associated :project, on: :update

  belongs_to :project
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :first_name, length: {minimum: 1, message: "Cannot be blank"} #, presence: true
  validates :last_name, length: {minimum: 1, message: "Cannot be blank"} #, presence: true
  validates :email, format: { message: "Must be a valid email", with: /.+@.+/} #, presence: true

  has_secure_password

  def admin?
    self.role == 'admin'
  end

  def fullname
    return self.first_name + ' ' + self.last_name
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  # Methods to provide user roles for controllers
  #
  def require_user
    redirect_to '/login' unless current_user
  end

  def require_admin
    redirect_to '/' unless current_user.admin?
  end

end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  before_action :require_admin, only: [:edit, :destroy]
  before_action :require_user, only: [:index, :show, :update, :new, :create]

  #def index
  #  @features = Feature.all
  #end

  def show
    @feature = Feature.find(params[:id])
  end

  def edit
    @project = Project.find(params[:project_id])
    @feature = Feature.find(params[:id])
  end

  def update
    @project = Project.find(params[:project_id])
    @feature = Feature.find(params[:id])
    @originalFeatureTitle = @feature.title
    if @feature.update(feature_params)
      #redirect_to(:action => 'show', :id => @feature.project.id)
      redirect_to project_path(@feature.project.id)
    else
      render 'edit'
    end
  end

  def new
    @project = Project.find(params[:project_id])
    @feature = Feature.new
  end

  def create
    @project = Project.find(params[:project_id])
    @feature = @project.feature.create(feature_params)
    if @feature.save
      redirect_to project_path(@project)
    else
      render 'new'
    end
  end

  def destroy
    @project = Project.find(params[:project_id])
    @feature = @project.feature.find(params[:id])
    @feature.destroy
    redirect_to project_path(@project)
  end

  private
  def feature_params
    params.require(:feature).permit(:title, :description, :status)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_admin, only: [:edit, :destroy]
  before_action :require_user, only: [:index, :show, :update, :new, :create]

  @currentPage;

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @currentPage = 'edit'
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @originalProjectTitle = @project.title
    if @project.update(project_params)
      redirect_to(:action => 'show', :id => @project.id)
    else
      @currentPage = 'edit'
      render 'edit'
    end
  end

  def new
    @currentPage = 'new'
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path
    else
      @currentPage = 'new'
      render 'new'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

  private
  def project_params
    params.require(:project).permit(:title, :description, :dev_env, :prod_env, :language_desc)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # sessions_controller.rb
  # Handles the site login functionality.
  #

  def new
  end

  def create
    @user = User.find_by_email(params[:session][:email]) #inserted [:session] back into params list
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to projects_path
    else
      @loginErrors = "Email or password was incorrect"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_admin, only: [:edit, :destroy]
  before_action :require_user, only: [:show, :update, :new, :create]

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @project = Project.find(params[:project_id])
    @task = Task.find(params[:id])
  end

  def update
    @project = Project.find(params[:project_id])
    @task = Task.find(params[:id])
    @originalTaskTitle = @task.title
    if @task.update(task_params)
      #redirect_to(:action => 'show', :id => @task.project.id)
      redirect_to project_path(@task.project.id)
    else
      render 'edit'
    end
  end

  def new
    @project = Project.find(params[:project_id])
    @task = Task.new
  end

  def create
    @project = Project.find(params[:project_id])
    @task = @project.task.create(task_params)
    if @task.save
      redirect_to project_path(@project)
    else
      render 'new'
    end
  end

  def destroy
    @project = Project.find(params[:project_id])
    @task = @project.task.find(params[:id])
    @task.destroy
    redirect_to project_path(@project)
  end

  private
  def task_params
    params.require(:task).permit(:title, :description, :status)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to projects_path
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/features/_form.html.erb
<%= form_for([@project, @feature]) do |t| %>

  <%= t.label :title %>
    <span class="error">
      <%= @feature.errors[:title][0] %>
    </span>
  <%= t.text_field :title %>

  <%= t.label :description %>
    <span class="error">
      <%= @feature.errors[:description][0] %>
    </span>
  <%= t.text_area :description %>

  <%= t.label :status %>
    <span class="error">
      <%= @feature.errors[:status][0] %>
    </span>
  <%= t.text_field :status %>

  <div class="formButtons">
    <%= t.submit %>
    <%= button_tag "Reset", type: :reset %><br><br>
    <%= link_to 'Cancel', project_path(@project) %>
  </div>
<% end %>

app/views/features/edit.html.erb
<h3>Editing Feature: <%= @originalFeatureTitle %> for <%= @project.title %>
  <% if @feature.errors.any? %>
    Error
  <% end %>
</h3>

<%= render 'features/form' %>

app/views/features/new.html.erb
<h3>New Feature for <%= @project.title %>
  <% if @feature.errors.any? %>
    Error
  <% end %>
</h3>

<%= render 'features/form' %>

app/views/features/show.html.erb
Show Feature

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project Manager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="frame center">
    <div class="col-1">
      <div>
        <h2>Project Manager</h2>
      </div>

      <% if current_user %>
        <div>
          <%= current_user.fullname %><br>
          <% if current_user.admin? %>
            <span>Admin</span>
          <% else %>
            <span>User</span>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="col-1 topMargin10">
      <nav>
        <% if current_user %>
          <%= link_to 'Projects Page', projects_path %> |
          <%= link_to "Log out", logout_path, method: "delete" %>
        <% else %>
          <%= link_to "Login", '/login' %> |
          <%= link_to "Signup", '/signup' %>
        <% end %>
      </nav>
    </div>
</header>

<section>
  <%= yield %>
</section>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |p| %>

  <%= p.label :title %>
  <span class="error">
    <%= @project.errors[:title][0] %>
  </span>
  <%= p.text_field :title %>

  <%= p.label :description %>
  <span class="error">
    <%= @project.errors[:description][0] %>
  </span>
  <%= p.text_area :description %>

  <%= p.label :dev_env, "Development environment" %>
  <span class="error">
    <%= @project.errors[:dev_env][0] %>
  </span>
  <%= p.text_area :dev_env %>

  <%= p.label :prod_env, "Production environment" %>
  <span class="error">
    <%= @project.errors[:prod_env][0] %>
  </span>
  <%= p.text_area :prod_env %>

  <%= p.label :language_desc, "Language description" %>
  <span class="error">
    <%= @project.errors[:language_desc][0] %>
  </span>
  <%= p.text_area :language_desc %>

  <div class="formButtons">
    <%= p.submit :Submit %>
    <%= button_tag "Reset", type: :reset %><br><br>
    <% if @currentPage == 'new' %>
      <%= link_to 'Cancel', projects_path %>
    <% elsif @currentPage == 'edit' %>
      <%= link_to 'Cancel', project_path(@project) %>
    <% end %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h3>Editing Project: <%= @originalProjectTitle %>
  <% if @project.errors.any? %>
    Error
  <% end %>
</h3>

<%= render 'projects/form' %>

app/views/projects/index.html.erb
<h2>Projects</h2>
<br>
<% if current_user.admin? %>
  <%= link_to "Create New Project", new_project_path %><br>
<% end %>
<br>
<table class="tableCSS">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>More Info</th>
  </tr>
<% @projects.each do |p| %>
  <tr>
    <td><%= p.title %></td>
    <td><%= p.description %></td>
    <td><%= link_to 'More Project', project_path(p) %></td>
  </tr>
<% end %>

</table><br>

app/views/projects/new.html.erb
<h3>Create a New Project
  <% if @project.errors.any? %>
    Error
  <% end %>
</h3>

<%= render 'projects/form' %>

app/views/projects/show.html.erb
<h3><%= @project.title %></h3>

<% if current_user.admin? %>
<%= link_to 'Edit Project', edit_project_path(@project) %> |
<%= link_to 'Remove Project', project_path(@project), method: :delete, data: { confirm: 'Deleting ' + @project.title + '. Are you sure?' } %>
<% end %>

<div class="frame">

  <div class="col-2 alignLeft"><!--alignLeft-->
    <h4 class="lightBlueText">Project Description:</h4>
    <div>
      <%= @project.description %>
    </div>
    <h4 class="lightBlueText">Project Development Environment:</h4>
    <div>
      <%= @project.dev_env %>
    </div>
    <h4 class="lightBlueText">Project Production Environment:</h4>
    <div>
      <%= @project.prod_env %>
    </div>
    <h4 class="lightBlueText">Project Language Description:</h4>
    <div>
      <%= @project.language_desc %>
    </div>
  </div>

  <div class="col-2">
    <h4>Features</h4>
    <% if current_user.admin? %>
    <%= link_to 'Create New Feature', new_feature_path(:project_id => @project.id) %><br><br>
    <% end %>
    <table class="tableCSS">
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Status</th>
        <% if current_user.admin? %>
        <th>Actions</th>
        <% end %>
      </tr>
      <% @project.feature.each do |feature| %>
      <tr>
        <td><%= feature.title %> <br></td>
        <td><%= feature.description %> <br></td>
        <td><%= feature.status %> <br></td>
        <% if current_user.admin? %>
        <td>
          <%= link_to 'Edit', edit_feature_path(feature, :project_id => @project.id) %> |
          <%= link_to 'Delete', [feature.project, feature], method: :delete, data: { confirm: 'Deleting ' + feature.title + '. Are you sure?' } %>
        </td>
        <% end %>
      </tr>
      <% end %>
    </table>
  </div>

</div>

<br>
<hr>
<br>

<div>
  <h4>Tasks</h4>

  <% if current_user.admin? %>
  <%= link_to 'Create New Task', new_task_path(:project_id => @project.id) %><br><br>
  <% end %>

  <table class="tableCSS">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Status</th>
      <% if current_user.admin? %>
      <th>Actions</th>
      <% end %>
    </tr>
    <% @project.task.each do |task| %>
    <tr>
      <td><%= task.title %> <br></td>
      <td><%= task.description %> <br></td>
      <td><%= task.status %> <br></td>
      <% if current_user.admin? %>
      <td>
        <%= link_to 'Edit', edit_task_path(task, :project_id => @project.id) %> |
        <%= link_to 'Delete', [task.project, task], method: :delete, data: { confirm: 'Deleting ' + task.title + '. Are you sure?' } %>
      </td>
      <% end %>
    </tr>
    <% end %>
  </table>
</div>

app/views/tasks/_form.html.erb
<%= form_for([@project, @task]) do |t| %>

  <%= t.label :title %>
    <span class="error">
      <%= @task.errors[:title][0] %>
    </span>
  <%= t.text_field :title %>

  <%= t.label :description %>
    <span class="error">
      <%= @task.errors[:description][0] %>
    </span>
  <%= t.text_area :description %>

  <%= t.label :status %>
    <span class="error">
      <%= @task.errors[:status][0] %>
    </span>
  <%= t.text_field :status %>

  <div class="formButtons">
    <%= t.submit %>
    <%= button_tag "Reset", type: :reset %><br><br>
    <%= link_to 'Cancel', project_path(@project) %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h3>Editing Task: <%= @originalTaskTitle %> for <%= @project.title %>
  <% if @task.errors.any? %>
    Error
  <% end %>
</h3>

<%= render 'tasks/form' %>

app/views/tasks/new.html.erb
<h3>New Task for <%= @project.title %>
  <% if @task.errors.any? %>
    Error
  <% end %>
</h3>

<%= render 'tasks/form' %>

app/views/tasks/show.html.erb
Show Task

app/views/users/new.html.erb
<div class="login">
  <div class="container">
    <div class="form">

    <h1>Sign up
      <% if @user.errors.any? %>
        Error
      <% end %>
    </h1>
    <%= form_for(:user, url: signup_path) do |f| %>

      <%= f.label :first_name %>
      <span class="error">
        <%= @user.errors[:first_name][0] %>
      </span>
      <%= f.text_field :first_name %>

      <%= f.label :last_name %>
      <span class="error">
        <%= @user.errors[:last_name][0] %>
      </span>
      <%= f.text_field :last_name%>

      <%= f.label :email %>
      <span class="error">
        <%= @user.errors[:email][0] %>
      </span>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <span class="error">
        <%= @user.errors[:password][0] %>
      </span>
      <%= f.password_field :password %>

      <div class="formButtons">
        <%= f.submit "Create an account", class: "btn-submit" %>
      </div>
    <% end %>

    </div>
  </div>
</div>